apiVersion: v1
kind: Secret
metadata:
  name: {{ include "human-call-filter.fullname" . }}-cloudsql-instance-credentials
  labels:
    app: {{ include "human-call-filter.name" . }}
    chart: {{ include "human-call-filter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials:
    username: {{ ".Values.db.username" | b64enc }}
    password: {{ ".Values.db.password" | b64enc }}
