apiVersion: v1
kind: Secret
metadata:
  name: {{ include "human-call-filter.fullname" . }}-secrets
  labels:
    app: {{ include "human-call-filter.name" . }}
    chart: {{ include "human-call-filter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  voip_address: {{ .Values.voip.address | b64enc }}
  db_password: {{ .Values.db.password | b64enc }}
