apiVersion: v1
kind: Service
metadata:
  name: {{ include "human-call-filter.fullname" . }}
  labels:
    app: {{ include "human-call-filter.name" . }}
    chart: {{ include "human-call-filter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.calls }}
      targetPort: calls
      protocol: TCP
      name: calls
    - port: {{ .Values.service.ports.dashboard }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard

  selector:
    app: {{ include "human-call-filter.name" . }}
    release: {{ .Release.Name }}
